package ru.zumber.testchrisproject.measurement;

import jakarta.persistence.*;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;

import java.math.BigDecimal;
import java.time.LocalDate;

@Data
@Entity
@Table(name = "measurement")
@NoArgsConstructor
@AllArgsConstructor
public class Measurement {
    @Id
    @GeneratedValue(strategy = GenerationType.IDENTITY)
    private Long id;
    @Column
    private String userName;
    @Column
    @Enumerated(EnumType.ORDINAL)
    private MeasurementType measurementType;
    @Column
    private BigDecimal value;
    @Column
    private LocalDate startDate;
    @Column
    private LocalDate endDate;
}



//create table measurement
//        (
//                id               bigint generated by default as identity primary key,
//                user_name        varchar(50) not null,
//measurement_type integer     not null,
//value            decimal     not null,
//start_date       date        not null,
//end_date         date        not null
//        )
